# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# site settings
title: Iraquitan
email: iraquitanfilho@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Computer Science BS by Federal University of Pará, Belém, Brazil. Full Stack
  Web Development Nanodegree by Udacity. Currently working on research field,
  with Brain Computer Interfaces (BCI).
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://iraquitan.github.io" # the base hostname & protocol for your site

# collections
collections:
  posts:
    permalink: /blog/:categories/:year/:month/:day/:title/

# exclude
exclude: [assets, node_modules, Gemfile, Gemfile.lock, gulpfile.js, package.json]

# timezone
timezone: America/Belem

# build settings
markdown: kramdown

# plugins
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-coffeescript
