# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
# Plugins
gems:
  - jekyll-sitemap
  - jekyll-assets
  - bourbon
  - neat
  - sass

assets:
  prefix: "/assets"
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets

# Collections
collections:
  projects:
    output: true

# Site settings
title: Iraquitan
email: iraquitanfilho@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://iraquitan.github.io" # the base hostname & protocol for your site

# Social profiles
social-profiles:
  - username: iraquitan
    base-url: 'github.com/'
    fa-icon: 'github-alt'
  - username: iraquitan
    base-url: 'codepen.io/'
    fa-icon: 'codepen'
  - username: iraquitan_filho
    base-url: 'twitter.com/'
    fa-icon: 'twitter'
  - username: iraquitan
    base-url: 'linkedin.com/in/'
    fa-icon: 'linkedin'

# Build settings
markdown: kramdown
