# Social profiles
- username: iraquitan
  base-url: 'github.com/'
  fa-icon: 'github-alt'
- username: iraquitan
  base-url: 'codepen.io/'
  fa-icon: 'codepen'
- username: iraquitan_filho
  base-url: 'twitter.com/'
  fa-icon: 'twitter'
- username: iraquitan
  base-url: 'linkedin.com/in/'
  fa-icon: 'linkedin'
